apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy17
  labels:
    app: autodeploy17
  namespace: namespace-workflow-1710949382827
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy17
  template:
    metadata:
      labels:
        app: autodeploy17
    spec:
      containers:
        - name: autodeploy17
          image: acrworkflow1710949382827.azurecr.io/image-workflow-1710949382827:latest
          ports:
            - containerPort: 5000